//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.19.0
//     from Assets/Scripts/PerkinsActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Scripts/PerkinsActions.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @PerkinsActions: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @PerkinsActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""PerkinsActions"",
    ""maps"": [
        {
            ""name"": ""PerkinsBrailer"",
            ""id"": ""cfb38727-aa94-4b15-b2c5-8556eb58272b"",
            ""actions"": [
                {
                    ""name"": ""Dot0"",
                    ""type"": ""Button"",
                    ""id"": ""d0f170c4-6c99-4f43-ae73-3e7afa62ff7a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dot1"",
                    ""type"": ""Button"",
                    ""id"": ""61811dd3-1a01-4bc9-b59a-dfb9df6bcc53"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dot2"",
                    ""type"": ""Button"",
                    ""id"": ""38b655a8-8b4a-4f60-b82d-15ab1bb55770"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dot3"",
                    ""type"": ""Button"",
                    ""id"": ""b0c85441-b7b5-4142-a4af-31c0deb0c4d3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dot4"",
                    ""type"": ""Button"",
                    ""id"": ""dcc10467-92cc-4b56-8cba-ae5394fac420"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dot5"",
                    ""type"": ""Button"",
                    ""id"": ""c5246269-3b4b-42af-8c2c-89aebd659895"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Space"",
                    ""type"": ""Button"",
                    ""id"": ""02389eb2-4790-4998-ac8c-15e931e83176"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Delete"",
                    ""type"": ""Button"",
                    ""id"": ""30d256ec-6634-4b29-b4b8-de377c818eb5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""85f5458c-19ec-46f1-8e92-5e4ff4807f8c"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dot0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5e873d04-9da1-4f38-8999-75f6e7cdb4e4"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dot1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""148c3405-28e9-42d6-b3e9-1a5a24c4762a"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dot2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8ba402ef-c7ea-4294-b36b-e3a516a0c0a5"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dot3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dd1820d0-7d91-43e6-b471-e6f06c7bf113"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dot4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""143177f6-d334-4f2a-b70e-381b848a86fb"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dot5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2982e68d-cb8b-4736-8bd6-448bb52b30d2"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Space"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4940bac2-601a-4f2a-8779-7bfe626493ed"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Delete"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PerkinsBrailer
        m_PerkinsBrailer = asset.FindActionMap("PerkinsBrailer", throwIfNotFound: true);
        m_PerkinsBrailer_Dot0 = m_PerkinsBrailer.FindAction("Dot0", throwIfNotFound: true);
        m_PerkinsBrailer_Dot1 = m_PerkinsBrailer.FindAction("Dot1", throwIfNotFound: true);
        m_PerkinsBrailer_Dot2 = m_PerkinsBrailer.FindAction("Dot2", throwIfNotFound: true);
        m_PerkinsBrailer_Dot3 = m_PerkinsBrailer.FindAction("Dot3", throwIfNotFound: true);
        m_PerkinsBrailer_Dot4 = m_PerkinsBrailer.FindAction("Dot4", throwIfNotFound: true);
        m_PerkinsBrailer_Dot5 = m_PerkinsBrailer.FindAction("Dot5", throwIfNotFound: true);
        m_PerkinsBrailer_Space = m_PerkinsBrailer.FindAction("Space", throwIfNotFound: true);
        m_PerkinsBrailer_Delete = m_PerkinsBrailer.FindAction("Delete", throwIfNotFound: true);
    }

    ~@PerkinsActions()
    {
        UnityEngine.Debug.Assert(!m_PerkinsBrailer.enabled, "This will cause a leak and performance issues, PerkinsActions.PerkinsBrailer.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PerkinsBrailer
    private readonly InputActionMap m_PerkinsBrailer;
    private List<IPerkinsBrailerActions> m_PerkinsBrailerActionsCallbackInterfaces = new List<IPerkinsBrailerActions>();
    private readonly InputAction m_PerkinsBrailer_Dot0;
    private readonly InputAction m_PerkinsBrailer_Dot1;
    private readonly InputAction m_PerkinsBrailer_Dot2;
    private readonly InputAction m_PerkinsBrailer_Dot3;
    private readonly InputAction m_PerkinsBrailer_Dot4;
    private readonly InputAction m_PerkinsBrailer_Dot5;
    private readonly InputAction m_PerkinsBrailer_Space;
    private readonly InputAction m_PerkinsBrailer_Delete;
    /// <summary>
    /// Provides access to input actions defined in input action map "PerkinsBrailer".
    /// </summary>
    public struct PerkinsBrailerActions
    {
        private @PerkinsActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public PerkinsBrailerActions(@PerkinsActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "PerkinsBrailer/Dot0".
        /// </summary>
        public InputAction @Dot0 => m_Wrapper.m_PerkinsBrailer_Dot0;
        /// <summary>
        /// Provides access to the underlying input action "PerkinsBrailer/Dot1".
        /// </summary>
        public InputAction @Dot1 => m_Wrapper.m_PerkinsBrailer_Dot1;
        /// <summary>
        /// Provides access to the underlying input action "PerkinsBrailer/Dot2".
        /// </summary>
        public InputAction @Dot2 => m_Wrapper.m_PerkinsBrailer_Dot2;
        /// <summary>
        /// Provides access to the underlying input action "PerkinsBrailer/Dot3".
        /// </summary>
        public InputAction @Dot3 => m_Wrapper.m_PerkinsBrailer_Dot3;
        /// <summary>
        /// Provides access to the underlying input action "PerkinsBrailer/Dot4".
        /// </summary>
        public InputAction @Dot4 => m_Wrapper.m_PerkinsBrailer_Dot4;
        /// <summary>
        /// Provides access to the underlying input action "PerkinsBrailer/Dot5".
        /// </summary>
        public InputAction @Dot5 => m_Wrapper.m_PerkinsBrailer_Dot5;
        /// <summary>
        /// Provides access to the underlying input action "PerkinsBrailer/Space".
        /// </summary>
        public InputAction @Space => m_Wrapper.m_PerkinsBrailer_Space;
        /// <summary>
        /// Provides access to the underlying input action "PerkinsBrailer/Delete".
        /// </summary>
        public InputAction @Delete => m_Wrapper.m_PerkinsBrailer_Delete;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_PerkinsBrailer; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="PerkinsBrailerActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(PerkinsBrailerActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="PerkinsBrailerActions" />
        public void AddCallbacks(IPerkinsBrailerActions instance)
        {
            if (instance == null || m_Wrapper.m_PerkinsBrailerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PerkinsBrailerActionsCallbackInterfaces.Add(instance);
            @Dot0.started += instance.OnDot0;
            @Dot0.performed += instance.OnDot0;
            @Dot0.canceled += instance.OnDot0;
            @Dot1.started += instance.OnDot1;
            @Dot1.performed += instance.OnDot1;
            @Dot1.canceled += instance.OnDot1;
            @Dot2.started += instance.OnDot2;
            @Dot2.performed += instance.OnDot2;
            @Dot2.canceled += instance.OnDot2;
            @Dot3.started += instance.OnDot3;
            @Dot3.performed += instance.OnDot3;
            @Dot3.canceled += instance.OnDot3;
            @Dot4.started += instance.OnDot4;
            @Dot4.performed += instance.OnDot4;
            @Dot4.canceled += instance.OnDot4;
            @Dot5.started += instance.OnDot5;
            @Dot5.performed += instance.OnDot5;
            @Dot5.canceled += instance.OnDot5;
            @Space.started += instance.OnSpace;
            @Space.performed += instance.OnSpace;
            @Space.canceled += instance.OnSpace;
            @Delete.started += instance.OnDelete;
            @Delete.performed += instance.OnDelete;
            @Delete.canceled += instance.OnDelete;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="PerkinsBrailerActions" />
        private void UnregisterCallbacks(IPerkinsBrailerActions instance)
        {
            @Dot0.started -= instance.OnDot0;
            @Dot0.performed -= instance.OnDot0;
            @Dot0.canceled -= instance.OnDot0;
            @Dot1.started -= instance.OnDot1;
            @Dot1.performed -= instance.OnDot1;
            @Dot1.canceled -= instance.OnDot1;
            @Dot2.started -= instance.OnDot2;
            @Dot2.performed -= instance.OnDot2;
            @Dot2.canceled -= instance.OnDot2;
            @Dot3.started -= instance.OnDot3;
            @Dot3.performed -= instance.OnDot3;
            @Dot3.canceled -= instance.OnDot3;
            @Dot4.started -= instance.OnDot4;
            @Dot4.performed -= instance.OnDot4;
            @Dot4.canceled -= instance.OnDot4;
            @Dot5.started -= instance.OnDot5;
            @Dot5.performed -= instance.OnDot5;
            @Dot5.canceled -= instance.OnDot5;
            @Space.started -= instance.OnSpace;
            @Space.performed -= instance.OnSpace;
            @Space.canceled -= instance.OnSpace;
            @Delete.started -= instance.OnDelete;
            @Delete.performed -= instance.OnDelete;
            @Delete.canceled -= instance.OnDelete;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PerkinsBrailerActions.UnregisterCallbacks(IPerkinsBrailerActions)" />.
        /// </summary>
        /// <seealso cref="PerkinsBrailerActions.UnregisterCallbacks(IPerkinsBrailerActions)" />
        public void RemoveCallbacks(IPerkinsBrailerActions instance)
        {
            if (m_Wrapper.m_PerkinsBrailerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="PerkinsBrailerActions.AddCallbacks(IPerkinsBrailerActions)" />
        /// <seealso cref="PerkinsBrailerActions.RemoveCallbacks(IPerkinsBrailerActions)" />
        /// <seealso cref="PerkinsBrailerActions.UnregisterCallbacks(IPerkinsBrailerActions)" />
        public void SetCallbacks(IPerkinsBrailerActions instance)
        {
            foreach (var item in m_Wrapper.m_PerkinsBrailerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PerkinsBrailerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="PerkinsBrailerActions" /> instance referencing this action map.
    /// </summary>
    public PerkinsBrailerActions @PerkinsBrailer => new PerkinsBrailerActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "PerkinsBrailer" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="PerkinsBrailerActions.AddCallbacks(IPerkinsBrailerActions)" />
    /// <seealso cref="PerkinsBrailerActions.RemoveCallbacks(IPerkinsBrailerActions)" />
    public interface IPerkinsBrailerActions
    {
        /// <summary>
        /// Method invoked when associated input action "Dot0" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDot0(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Dot1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDot1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Dot2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDot2(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Dot3" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDot3(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Dot4" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDot4(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Dot5" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDot5(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Space" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSpace(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Delete" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDelete(InputAction.CallbackContext context);
    }
}
