//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.19.0
//     from Assets/Scripts/BrailleSettings.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Scripts/BrailleSettings.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @BrailleControls: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @BrailleControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""BrailleSettings"",
    ""maps"": [
        {
            ""name"": ""BrailleSettings"",
            ""id"": ""8642e1a8-8a31-41df-afe5-3f1a17fa2605"",
            ""actions"": [
                {
                    ""name"": ""BrailleSizeUp"",
                    ""type"": ""Button"",
                    ""id"": ""7046ee3e-d511-409b-9697-8f97e4a7cb13"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BrailleSizeDown"",
                    ""type"": ""Button"",
                    ""id"": ""8e6d8524-0d76-463f-beb6-98f810fbb17d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DotSizeUp"",
                    ""type"": ""Button"",
                    ""id"": ""7972c99c-17ae-4542-81e4-e10f61942b2c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DotSizeDown"",
                    ""type"": ""Button"",
                    ""id"": ""f0bc8a25-da74-44de-bbcf-61c7d2fd2fdd"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BrailleSpacingUp"",
                    ""type"": ""Button"",
                    ""id"": ""b0a089e0-69ef-4c67-bf91-f9e6e18bfc2e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BrailleSpacingDown"",
                    ""type"": ""Button"",
                    ""id"": ""47a3deb9-66a9-4b85-9c6b-a0a56386a504"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LineSpacingUp"",
                    ""type"": ""Button"",
                    ""id"": ""953c81c3-b673-46d1-81e2-39b110af2311"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LineSpacingDown"",
                    ""type"": ""Button"",
                    ""id"": ""f968fbb2-d695-4b55-a07b-61a399977475"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""cf92df46-7c3f-4f54-bd4f-24b9e535c2cf"",
                    ""path"": ""<Keyboard>/f1"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BrailleSizeUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""373f0f76-73ee-4ceb-a30a-e0eab53f3a69"",
                    ""path"": ""<Keyboard>/f2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BrailleSizeDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""199a3582-7ff5-46c3-ae6b-36ccab32be96"",
                    ""path"": ""<Keyboard>/f3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DotSizeUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4b1db400-faf7-4f02-bd2e-ca23ca9129a8"",
                    ""path"": ""<Keyboard>/f4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DotSizeDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""83657769-4ec5-4341-9a91-c98bfa5ddb03"",
                    ""path"": ""<Keyboard>/f5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BrailleSpacingUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d73cdd63-4679-4c9b-a3e0-233700ec7b0a"",
                    ""path"": ""<Keyboard>/f6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BrailleSpacingDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a149cae9-abd9-4c7d-89cb-183eb6a2ac8e"",
                    ""path"": ""<Keyboard>/f7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LineSpacingUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b9335d15-3625-4b27-90dc-3d63f4b995c7"",
                    ""path"": ""<Keyboard>/f8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LineSpacingDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // BrailleSettings
        m_BrailleSettings = asset.FindActionMap("BrailleSettings", throwIfNotFound: true);
        m_BrailleSettings_BrailleSizeUp = m_BrailleSettings.FindAction("BrailleSizeUp", throwIfNotFound: true);
        m_BrailleSettings_BrailleSizeDown = m_BrailleSettings.FindAction("BrailleSizeDown", throwIfNotFound: true);
        m_BrailleSettings_DotSizeUp = m_BrailleSettings.FindAction("DotSizeUp", throwIfNotFound: true);
        m_BrailleSettings_DotSizeDown = m_BrailleSettings.FindAction("DotSizeDown", throwIfNotFound: true);
        m_BrailleSettings_BrailleSpacingUp = m_BrailleSettings.FindAction("BrailleSpacingUp", throwIfNotFound: true);
        m_BrailleSettings_BrailleSpacingDown = m_BrailleSettings.FindAction("BrailleSpacingDown", throwIfNotFound: true);
        m_BrailleSettings_LineSpacingUp = m_BrailleSettings.FindAction("LineSpacingUp", throwIfNotFound: true);
        m_BrailleSettings_LineSpacingDown = m_BrailleSettings.FindAction("LineSpacingDown", throwIfNotFound: true);
    }

    ~@BrailleControls()
    {
        UnityEngine.Debug.Assert(!m_BrailleSettings.enabled, "This will cause a leak and performance issues, BrailleControls.BrailleSettings.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // BrailleSettings
    private readonly InputActionMap m_BrailleSettings;
    private List<IBrailleSettingsActions> m_BrailleSettingsActionsCallbackInterfaces = new List<IBrailleSettingsActions>();
    private readonly InputAction m_BrailleSettings_BrailleSizeUp;
    private readonly InputAction m_BrailleSettings_BrailleSizeDown;
    private readonly InputAction m_BrailleSettings_DotSizeUp;
    private readonly InputAction m_BrailleSettings_DotSizeDown;
    private readonly InputAction m_BrailleSettings_BrailleSpacingUp;
    private readonly InputAction m_BrailleSettings_BrailleSpacingDown;
    private readonly InputAction m_BrailleSettings_LineSpacingUp;
    private readonly InputAction m_BrailleSettings_LineSpacingDown;
    /// <summary>
    /// Provides access to input actions defined in input action map "BrailleSettings".
    /// </summary>
    public struct BrailleSettingsActions
    {
        private @BrailleControls m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public BrailleSettingsActions(@BrailleControls wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "BrailleSettings/BrailleSizeUp".
        /// </summary>
        public InputAction @BrailleSizeUp => m_Wrapper.m_BrailleSettings_BrailleSizeUp;
        /// <summary>
        /// Provides access to the underlying input action "BrailleSettings/BrailleSizeDown".
        /// </summary>
        public InputAction @BrailleSizeDown => m_Wrapper.m_BrailleSettings_BrailleSizeDown;
        /// <summary>
        /// Provides access to the underlying input action "BrailleSettings/DotSizeUp".
        /// </summary>
        public InputAction @DotSizeUp => m_Wrapper.m_BrailleSettings_DotSizeUp;
        /// <summary>
        /// Provides access to the underlying input action "BrailleSettings/DotSizeDown".
        /// </summary>
        public InputAction @DotSizeDown => m_Wrapper.m_BrailleSettings_DotSizeDown;
        /// <summary>
        /// Provides access to the underlying input action "BrailleSettings/BrailleSpacingUp".
        /// </summary>
        public InputAction @BrailleSpacingUp => m_Wrapper.m_BrailleSettings_BrailleSpacingUp;
        /// <summary>
        /// Provides access to the underlying input action "BrailleSettings/BrailleSpacingDown".
        /// </summary>
        public InputAction @BrailleSpacingDown => m_Wrapper.m_BrailleSettings_BrailleSpacingDown;
        /// <summary>
        /// Provides access to the underlying input action "BrailleSettings/LineSpacingUp".
        /// </summary>
        public InputAction @LineSpacingUp => m_Wrapper.m_BrailleSettings_LineSpacingUp;
        /// <summary>
        /// Provides access to the underlying input action "BrailleSettings/LineSpacingDown".
        /// </summary>
        public InputAction @LineSpacingDown => m_Wrapper.m_BrailleSettings_LineSpacingDown;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_BrailleSettings; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="BrailleSettingsActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(BrailleSettingsActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="BrailleSettingsActions" />
        public void AddCallbacks(IBrailleSettingsActions instance)
        {
            if (instance == null || m_Wrapper.m_BrailleSettingsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_BrailleSettingsActionsCallbackInterfaces.Add(instance);
            @BrailleSizeUp.started += instance.OnBrailleSizeUp;
            @BrailleSizeUp.performed += instance.OnBrailleSizeUp;
            @BrailleSizeUp.canceled += instance.OnBrailleSizeUp;
            @BrailleSizeDown.started += instance.OnBrailleSizeDown;
            @BrailleSizeDown.performed += instance.OnBrailleSizeDown;
            @BrailleSizeDown.canceled += instance.OnBrailleSizeDown;
            @DotSizeUp.started += instance.OnDotSizeUp;
            @DotSizeUp.performed += instance.OnDotSizeUp;
            @DotSizeUp.canceled += instance.OnDotSizeUp;
            @DotSizeDown.started += instance.OnDotSizeDown;
            @DotSizeDown.performed += instance.OnDotSizeDown;
            @DotSizeDown.canceled += instance.OnDotSizeDown;
            @BrailleSpacingUp.started += instance.OnBrailleSpacingUp;
            @BrailleSpacingUp.performed += instance.OnBrailleSpacingUp;
            @BrailleSpacingUp.canceled += instance.OnBrailleSpacingUp;
            @BrailleSpacingDown.started += instance.OnBrailleSpacingDown;
            @BrailleSpacingDown.performed += instance.OnBrailleSpacingDown;
            @BrailleSpacingDown.canceled += instance.OnBrailleSpacingDown;
            @LineSpacingUp.started += instance.OnLineSpacingUp;
            @LineSpacingUp.performed += instance.OnLineSpacingUp;
            @LineSpacingUp.canceled += instance.OnLineSpacingUp;
            @LineSpacingDown.started += instance.OnLineSpacingDown;
            @LineSpacingDown.performed += instance.OnLineSpacingDown;
            @LineSpacingDown.canceled += instance.OnLineSpacingDown;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="BrailleSettingsActions" />
        private void UnregisterCallbacks(IBrailleSettingsActions instance)
        {
            @BrailleSizeUp.started -= instance.OnBrailleSizeUp;
            @BrailleSizeUp.performed -= instance.OnBrailleSizeUp;
            @BrailleSizeUp.canceled -= instance.OnBrailleSizeUp;
            @BrailleSizeDown.started -= instance.OnBrailleSizeDown;
            @BrailleSizeDown.performed -= instance.OnBrailleSizeDown;
            @BrailleSizeDown.canceled -= instance.OnBrailleSizeDown;
            @DotSizeUp.started -= instance.OnDotSizeUp;
            @DotSizeUp.performed -= instance.OnDotSizeUp;
            @DotSizeUp.canceled -= instance.OnDotSizeUp;
            @DotSizeDown.started -= instance.OnDotSizeDown;
            @DotSizeDown.performed -= instance.OnDotSizeDown;
            @DotSizeDown.canceled -= instance.OnDotSizeDown;
            @BrailleSpacingUp.started -= instance.OnBrailleSpacingUp;
            @BrailleSpacingUp.performed -= instance.OnBrailleSpacingUp;
            @BrailleSpacingUp.canceled -= instance.OnBrailleSpacingUp;
            @BrailleSpacingDown.started -= instance.OnBrailleSpacingDown;
            @BrailleSpacingDown.performed -= instance.OnBrailleSpacingDown;
            @BrailleSpacingDown.canceled -= instance.OnBrailleSpacingDown;
            @LineSpacingUp.started -= instance.OnLineSpacingUp;
            @LineSpacingUp.performed -= instance.OnLineSpacingUp;
            @LineSpacingUp.canceled -= instance.OnLineSpacingUp;
            @LineSpacingDown.started -= instance.OnLineSpacingDown;
            @LineSpacingDown.performed -= instance.OnLineSpacingDown;
            @LineSpacingDown.canceled -= instance.OnLineSpacingDown;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="BrailleSettingsActions.UnregisterCallbacks(IBrailleSettingsActions)" />.
        /// </summary>
        /// <seealso cref="BrailleSettingsActions.UnregisterCallbacks(IBrailleSettingsActions)" />
        public void RemoveCallbacks(IBrailleSettingsActions instance)
        {
            if (m_Wrapper.m_BrailleSettingsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="BrailleSettingsActions.AddCallbacks(IBrailleSettingsActions)" />
        /// <seealso cref="BrailleSettingsActions.RemoveCallbacks(IBrailleSettingsActions)" />
        /// <seealso cref="BrailleSettingsActions.UnregisterCallbacks(IBrailleSettingsActions)" />
        public void SetCallbacks(IBrailleSettingsActions instance)
        {
            foreach (var item in m_Wrapper.m_BrailleSettingsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_BrailleSettingsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="BrailleSettingsActions" /> instance referencing this action map.
    /// </summary>
    public BrailleSettingsActions @BrailleSettings => new BrailleSettingsActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "BrailleSettings" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="BrailleSettingsActions.AddCallbacks(IBrailleSettingsActions)" />
    /// <seealso cref="BrailleSettingsActions.RemoveCallbacks(IBrailleSettingsActions)" />
    public interface IBrailleSettingsActions
    {
        /// <summary>
        /// Method invoked when associated input action "BrailleSizeUp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnBrailleSizeUp(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "BrailleSizeDown" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnBrailleSizeDown(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "DotSizeUp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDotSizeUp(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "DotSizeDown" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDotSizeDown(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "BrailleSpacingUp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnBrailleSpacingUp(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "BrailleSpacingDown" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnBrailleSpacingDown(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LineSpacingUp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLineSpacingUp(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LineSpacingDown" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLineSpacingDown(InputAction.CallbackContext context);
    }
}
