//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.19.0
//     from Assets/Scripts/Settings/GameActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace IO
{
    /// <summary>
    /// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Scripts/Settings/GameActions.inputactions".
    /// </summary>
    /// <remarks>
    /// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
    /// </remarks>
    /// <example>
    /// <code>
    /// using namespace UnityEngine;
    /// using UnityEngine.InputSystem;
    ///
    /// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
    /// public class Example : MonoBehaviour, MyActions.IPlayerActions
    /// {
    ///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
    ///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
    ///
    ///     void Awake()
    ///     {
    ///         m_Actions = new MyActions_Actions();              // Create asset object.
    ///         m_Player = m_Actions.Player;                      // Extract action map object.
    ///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
    ///     }
    ///
    ///     void OnDestroy()
    ///     {
    ///         m_Actions.Dispose();                              // Destroy asset object.
    ///     }
    ///
    ///     void OnEnable()
    ///     {
    ///         m_Player.Enable();                                // Enable all actions within map.
    ///     }
    ///
    ///     void OnDisable()
    ///     {
    ///         m_Player.Disable();                               // Disable all actions within map.
    ///     }
    ///
    ///     #region Interface implementation of MyActions.IPlayerActions
    ///
    ///     // Invoked when "Move" action is either started, performed or canceled.
    ///     public void OnMove(InputAction.CallbackContext context)
    ///     {
    ///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
    ///     }
    ///
    ///     // Invoked when "Attack" action is either started, performed or canceled.
    ///     public void OnAttack(InputAction.CallbackContext context)
    ///     {
    ///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
    ///     }
    ///
    ///     #endregion
    /// }
    /// </code>
    /// </example>
    public partial class @GameActions: IInputActionCollection2, IDisposable
    {
        /// <summary>
        /// Provides access to the underlying asset instance.
        /// </summary>
        public InputActionAsset asset { get; }

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public @GameActions()
        {
            asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""GameActions"",
    ""maps"": [
        {
            ""name"": ""PerkinsBrailer"",
            ""id"": ""5c0322a0-2b7c-41d4-96d7-c9ed0ba7f0e4"",
            ""actions"": [
                {
                    ""name"": ""Dot0"",
                    ""type"": ""Button"",
                    ""id"": ""b1c319fb-d426-429f-8065-f34c7f46eb10"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dot1"",
                    ""type"": ""Button"",
                    ""id"": ""75426906-62fc-41a5-b4a3-9cf14672683d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dot2"",
                    ""type"": ""Button"",
                    ""id"": ""26d76ad9-e422-45e4-bb5f-0a2433e3c8c0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dot3"",
                    ""type"": ""Button"",
                    ""id"": ""ec902e29-2346-4d06-85bb-1715c56b0205"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dot4"",
                    ""type"": ""Button"",
                    ""id"": ""d3be0a1e-f422-4a2a-b32d-96063a1c6317"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dot5"",
                    ""type"": ""Button"",
                    ""id"": ""3725501b-cd31-494c-8dfb-c07445ef228c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Space"",
                    ""type"": ""Button"",
                    ""id"": ""c19364b2-9a56-4ed3-b4c7-06806d1ac702"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Delete"",
                    ""type"": ""Button"",
                    ""id"": ""bf986db2-29c1-44a2-8443-5831968709ac"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""cb6193f1-c6c6-4942-8219-ba1ad5e097d3"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dot0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2f69bb46-454d-426b-9509-e11ebc2fedc9"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dot1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""de5eaa06-8e12-43e1-a84a-d377d344ffeb"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dot2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""76e7e586-a3d0-4b46-92e1-514fa2a6711a"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dot3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""230c8187-d7ed-4277-8d49-ae2fc0c2c284"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dot4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""26c5b9de-5114-4cda-9dbc-fa1177645788"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dot5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""644dabb4-3992-4bae-9be4-507bf7cc6a23"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Space"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""25b6e0b0-6d1b-412f-923e-77aeca87caeb"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Delete"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""BrailleSettings"",
            ""id"": ""97912eb7-eefd-45f7-a82c-bc948080cf9f"",
            ""actions"": [
                {
                    ""name"": ""BrailleSizeUp"",
                    ""type"": ""Button"",
                    ""id"": ""a5a5b794-6c42-4935-824f-3d83a4bc3162"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BrailleSizeDown"",
                    ""type"": ""Button"",
                    ""id"": ""91087f4c-6700-441d-a54a-d7379e86609b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DotSizeUp"",
                    ""type"": ""Button"",
                    ""id"": ""7c5adfd4-fb8c-4ab4-b614-2d7a983a55d4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DotSizeDown"",
                    ""type"": ""Button"",
                    ""id"": ""02da410a-1bef-4492-87b9-fc6c97fa7204"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BrailleSpacingUp"",
                    ""type"": ""Button"",
                    ""id"": ""bab74876-d753-4e47-b6f5-b7b6a0eadf41"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BrailleSpacingDown"",
                    ""type"": ""Button"",
                    ""id"": ""a8c271b9-7c30-4cd6-a156-dd4cb718f4c1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LineSpacingUp"",
                    ""type"": ""Button"",
                    ""id"": ""9a49bae7-649a-4975-985a-1b79ff85a53e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LineSpacingDown"",
                    ""type"": ""Button"",
                    ""id"": ""5617dde9-2469-48c2-a7b5-12e34aba8977"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4b873958-caf9-44f5-a955-b29d608f350f"",
                    ""path"": ""<Keyboard>/f1"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BrailleSizeUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d4299620-add1-469b-9285-ac488a1f6271"",
                    ""path"": ""<Keyboard>/f2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BrailleSizeDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4e80fcbf-eba0-4e97-89ae-3fa4dd4913e3"",
                    ""path"": ""<Keyboard>/f3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DotSizeUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5c355cb8-f562-4038-8ab0-086764c1de0f"",
                    ""path"": ""<Keyboard>/f4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DotSizeDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""54252759-55a2-45f6-b136-5f8845eb3ac2"",
                    ""path"": ""<Keyboard>/f5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BrailleSpacingUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d921329a-f97c-4829-9812-63ffb356afe0"",
                    ""path"": ""<Keyboard>/f6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BrailleSpacingDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""08762b66-009a-4473-9546-d06d4cb6c1ad"",
                    ""path"": ""<Keyboard>/f7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LineSpacingUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a0fa835e-d05a-41b1-b99a-48dcabaf0336"",
                    ""path"": ""<Keyboard>/f8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LineSpacingDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Navigation"",
            ""id"": ""551f1fdd-0629-479f-ac77-27f5931e6de5"",
            ""actions"": [
                {
                    ""name"": ""next"",
                    ""type"": ""Button"",
                    ""id"": ""8cb8b65b-3f9d-4137-905a-92a450d5c08a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""prev"",
                    ""type"": ""Button"",
                    ""id"": ""e2cef3cf-fb95-4336-b071-7094ed7c10d9"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""answer0"",
                    ""type"": ""Button"",
                    ""id"": ""275fe278-a833-4619-8a97-8965ca105d61"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""answer1"",
                    ""type"": ""Button"",
                    ""id"": ""5b044e24-b65c-4e80-aab7-8eea6675adc7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""answer2"",
                    ""type"": ""Button"",
                    ""id"": ""16690296-570f-44f5-a834-07717440024b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""answer3"",
                    ""type"": ""Button"",
                    ""id"": ""328db5b8-d6c5-4f77-b82e-ecb9cc231905"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""answer4"",
                    ""type"": ""Button"",
                    ""id"": ""1f3c52b8-ea2c-4151-b25e-a2762125783d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""answer5"",
                    ""type"": ""Button"",
                    ""id"": ""7310f6c2-3f7c-4367-a6c3-5343e972af65"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""confirm"",
                    ""type"": ""Button"",
                    ""id"": ""d6966af9-abee-40a1-a1ab-1eb97c8d6876"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""35a2637c-64f0-4a39-9bd8-380c4274c339"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""next"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c9d455b9-feb1-4f01-8931-0eabedd05d6b"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""prev"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a4a871d3-8a7b-413e-aefa-a0833b78c0ee"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""answer0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b041919c-64a8-4b7a-9e78-166e63591f09"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""answer1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e4b9337f-b56b-4e99-ba2d-a46b45a56b37"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""answer2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cf913738-4302-481a-81cb-a9a6c194c5d9"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""answer3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c64a834c-6b0e-4178-9988-affcbdbcc59e"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""answer4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8f2d91d7-4349-4b86-85ec-f27e8eae42fd"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""answer5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""08a0e39d-6a68-4a78-96ab-1d4071e43b9d"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""confirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // PerkinsBrailer
            m_PerkinsBrailer = asset.FindActionMap("PerkinsBrailer", throwIfNotFound: true);
            m_PerkinsBrailer_Dot0 = m_PerkinsBrailer.FindAction("Dot0", throwIfNotFound: true);
            m_PerkinsBrailer_Dot1 = m_PerkinsBrailer.FindAction("Dot1", throwIfNotFound: true);
            m_PerkinsBrailer_Dot2 = m_PerkinsBrailer.FindAction("Dot2", throwIfNotFound: true);
            m_PerkinsBrailer_Dot3 = m_PerkinsBrailer.FindAction("Dot3", throwIfNotFound: true);
            m_PerkinsBrailer_Dot4 = m_PerkinsBrailer.FindAction("Dot4", throwIfNotFound: true);
            m_PerkinsBrailer_Dot5 = m_PerkinsBrailer.FindAction("Dot5", throwIfNotFound: true);
            m_PerkinsBrailer_Space = m_PerkinsBrailer.FindAction("Space", throwIfNotFound: true);
            m_PerkinsBrailer_Delete = m_PerkinsBrailer.FindAction("Delete", throwIfNotFound: true);
            // BrailleSettings
            m_BrailleSettings = asset.FindActionMap("BrailleSettings", throwIfNotFound: true);
            m_BrailleSettings_BrailleSizeUp = m_BrailleSettings.FindAction("BrailleSizeUp", throwIfNotFound: true);
            m_BrailleSettings_BrailleSizeDown = m_BrailleSettings.FindAction("BrailleSizeDown", throwIfNotFound: true);
            m_BrailleSettings_DotSizeUp = m_BrailleSettings.FindAction("DotSizeUp", throwIfNotFound: true);
            m_BrailleSettings_DotSizeDown = m_BrailleSettings.FindAction("DotSizeDown", throwIfNotFound: true);
            m_BrailleSettings_BrailleSpacingUp = m_BrailleSettings.FindAction("BrailleSpacingUp", throwIfNotFound: true);
            m_BrailleSettings_BrailleSpacingDown = m_BrailleSettings.FindAction("BrailleSpacingDown", throwIfNotFound: true);
            m_BrailleSettings_LineSpacingUp = m_BrailleSettings.FindAction("LineSpacingUp", throwIfNotFound: true);
            m_BrailleSettings_LineSpacingDown = m_BrailleSettings.FindAction("LineSpacingDown", throwIfNotFound: true);
            // Navigation
            m_Navigation = asset.FindActionMap("Navigation", throwIfNotFound: true);
            m_Navigation_next = m_Navigation.FindAction("next", throwIfNotFound: true);
            m_Navigation_prev = m_Navigation.FindAction("prev", throwIfNotFound: true);
            m_Navigation_answer0 = m_Navigation.FindAction("answer0", throwIfNotFound: true);
            m_Navigation_answer1 = m_Navigation.FindAction("answer1", throwIfNotFound: true);
            m_Navigation_answer2 = m_Navigation.FindAction("answer2", throwIfNotFound: true);
            m_Navigation_answer3 = m_Navigation.FindAction("answer3", throwIfNotFound: true);
            m_Navigation_answer4 = m_Navigation.FindAction("answer4", throwIfNotFound: true);
            m_Navigation_answer5 = m_Navigation.FindAction("answer5", throwIfNotFound: true);
            m_Navigation_confirm = m_Navigation.FindAction("confirm", throwIfNotFound: true);
        }

        ~@GameActions()
        {
            UnityEngine.Debug.Assert(!m_PerkinsBrailer.enabled, "This will cause a leak and performance issues, GameActions.PerkinsBrailer.Disable() has not been called.");
            UnityEngine.Debug.Assert(!m_BrailleSettings.enabled, "This will cause a leak and performance issues, GameActions.BrailleSettings.Disable() has not been called.");
            UnityEngine.Debug.Assert(!m_Navigation.enabled, "This will cause a leak and performance issues, GameActions.Navigation.Disable() has not been called.");
        }

        /// <summary>
        /// Destroys this asset and all associated <see cref="InputAction"/> instances.
        /// </summary>
        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
        public void Enable()
        {
            asset.Enable();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
        public void Disable()
        {
            asset.Disable();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
        public IEnumerable<InputBinding> bindings => asset.bindings;

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // PerkinsBrailer
        private readonly InputActionMap m_PerkinsBrailer;
        private List<IPerkinsBrailerActions> m_PerkinsBrailerActionsCallbackInterfaces = new List<IPerkinsBrailerActions>();
        private readonly InputAction m_PerkinsBrailer_Dot0;
        private readonly InputAction m_PerkinsBrailer_Dot1;
        private readonly InputAction m_PerkinsBrailer_Dot2;
        private readonly InputAction m_PerkinsBrailer_Dot3;
        private readonly InputAction m_PerkinsBrailer_Dot4;
        private readonly InputAction m_PerkinsBrailer_Dot5;
        private readonly InputAction m_PerkinsBrailer_Space;
        private readonly InputAction m_PerkinsBrailer_Delete;
        /// <summary>
        /// Provides access to input actions defined in input action map "PerkinsBrailer".
        /// </summary>
        public struct PerkinsBrailerActions
        {
            private @GameActions m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public PerkinsBrailerActions(@GameActions wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "PerkinsBrailer/Dot0".
            /// </summary>
            public InputAction @Dot0 => m_Wrapper.m_PerkinsBrailer_Dot0;
            /// <summary>
            /// Provides access to the underlying input action "PerkinsBrailer/Dot1".
            /// </summary>
            public InputAction @Dot1 => m_Wrapper.m_PerkinsBrailer_Dot1;
            /// <summary>
            /// Provides access to the underlying input action "PerkinsBrailer/Dot2".
            /// </summary>
            public InputAction @Dot2 => m_Wrapper.m_PerkinsBrailer_Dot2;
            /// <summary>
            /// Provides access to the underlying input action "PerkinsBrailer/Dot3".
            /// </summary>
            public InputAction @Dot3 => m_Wrapper.m_PerkinsBrailer_Dot3;
            /// <summary>
            /// Provides access to the underlying input action "PerkinsBrailer/Dot4".
            /// </summary>
            public InputAction @Dot4 => m_Wrapper.m_PerkinsBrailer_Dot4;
            /// <summary>
            /// Provides access to the underlying input action "PerkinsBrailer/Dot5".
            /// </summary>
            public InputAction @Dot5 => m_Wrapper.m_PerkinsBrailer_Dot5;
            /// <summary>
            /// Provides access to the underlying input action "PerkinsBrailer/Space".
            /// </summary>
            public InputAction @Space => m_Wrapper.m_PerkinsBrailer_Space;
            /// <summary>
            /// Provides access to the underlying input action "PerkinsBrailer/Delete".
            /// </summary>
            public InputAction @Delete => m_Wrapper.m_PerkinsBrailer_Delete;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_PerkinsBrailer; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="PerkinsBrailerActions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(PerkinsBrailerActions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="PerkinsBrailerActions" />
            public void AddCallbacks(IPerkinsBrailerActions instance)
            {
                if (instance == null || m_Wrapper.m_PerkinsBrailerActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_PerkinsBrailerActionsCallbackInterfaces.Add(instance);
                @Dot0.started += instance.OnDot0;
                @Dot0.performed += instance.OnDot0;
                @Dot0.canceled += instance.OnDot0;
                @Dot1.started += instance.OnDot1;
                @Dot1.performed += instance.OnDot1;
                @Dot1.canceled += instance.OnDot1;
                @Dot2.started += instance.OnDot2;
                @Dot2.performed += instance.OnDot2;
                @Dot2.canceled += instance.OnDot2;
                @Dot3.started += instance.OnDot3;
                @Dot3.performed += instance.OnDot3;
                @Dot3.canceled += instance.OnDot3;
                @Dot4.started += instance.OnDot4;
                @Dot4.performed += instance.OnDot4;
                @Dot4.canceled += instance.OnDot4;
                @Dot5.started += instance.OnDot5;
                @Dot5.performed += instance.OnDot5;
                @Dot5.canceled += instance.OnDot5;
                @Space.started += instance.OnSpace;
                @Space.performed += instance.OnSpace;
                @Space.canceled += instance.OnSpace;
                @Delete.started += instance.OnDelete;
                @Delete.performed += instance.OnDelete;
                @Delete.canceled += instance.OnDelete;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="PerkinsBrailerActions" />
            private void UnregisterCallbacks(IPerkinsBrailerActions instance)
            {
                @Dot0.started -= instance.OnDot0;
                @Dot0.performed -= instance.OnDot0;
                @Dot0.canceled -= instance.OnDot0;
                @Dot1.started -= instance.OnDot1;
                @Dot1.performed -= instance.OnDot1;
                @Dot1.canceled -= instance.OnDot1;
                @Dot2.started -= instance.OnDot2;
                @Dot2.performed -= instance.OnDot2;
                @Dot2.canceled -= instance.OnDot2;
                @Dot3.started -= instance.OnDot3;
                @Dot3.performed -= instance.OnDot3;
                @Dot3.canceled -= instance.OnDot3;
                @Dot4.started -= instance.OnDot4;
                @Dot4.performed -= instance.OnDot4;
                @Dot4.canceled -= instance.OnDot4;
                @Dot5.started -= instance.OnDot5;
                @Dot5.performed -= instance.OnDot5;
                @Dot5.canceled -= instance.OnDot5;
                @Space.started -= instance.OnSpace;
                @Space.performed -= instance.OnSpace;
                @Space.canceled -= instance.OnSpace;
                @Delete.started -= instance.OnDelete;
                @Delete.performed -= instance.OnDelete;
                @Delete.canceled -= instance.OnDelete;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PerkinsBrailerActions.UnregisterCallbacks(IPerkinsBrailerActions)" />.
            /// </summary>
            /// <seealso cref="PerkinsBrailerActions.UnregisterCallbacks(IPerkinsBrailerActions)" />
            public void RemoveCallbacks(IPerkinsBrailerActions instance)
            {
                if (m_Wrapper.m_PerkinsBrailerActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="PerkinsBrailerActions.AddCallbacks(IPerkinsBrailerActions)" />
            /// <seealso cref="PerkinsBrailerActions.RemoveCallbacks(IPerkinsBrailerActions)" />
            /// <seealso cref="PerkinsBrailerActions.UnregisterCallbacks(IPerkinsBrailerActions)" />
            public void SetCallbacks(IPerkinsBrailerActions instance)
            {
                foreach (var item in m_Wrapper.m_PerkinsBrailerActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_PerkinsBrailerActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="PerkinsBrailerActions" /> instance referencing this action map.
        /// </summary>
        public PerkinsBrailerActions @PerkinsBrailer => new PerkinsBrailerActions(this);

        // BrailleSettings
        private readonly InputActionMap m_BrailleSettings;
        private List<IBrailleSettingsActions> m_BrailleSettingsActionsCallbackInterfaces = new List<IBrailleSettingsActions>();
        private readonly InputAction m_BrailleSettings_BrailleSizeUp;
        private readonly InputAction m_BrailleSettings_BrailleSizeDown;
        private readonly InputAction m_BrailleSettings_DotSizeUp;
        private readonly InputAction m_BrailleSettings_DotSizeDown;
        private readonly InputAction m_BrailleSettings_BrailleSpacingUp;
        private readonly InputAction m_BrailleSettings_BrailleSpacingDown;
        private readonly InputAction m_BrailleSettings_LineSpacingUp;
        private readonly InputAction m_BrailleSettings_LineSpacingDown;
        /// <summary>
        /// Provides access to input actions defined in input action map "BrailleSettings".
        /// </summary>
        public struct BrailleSettingsActions
        {
            private @GameActions m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public BrailleSettingsActions(@GameActions wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "BrailleSettings/BrailleSizeUp".
            /// </summary>
            public InputAction @BrailleSizeUp => m_Wrapper.m_BrailleSettings_BrailleSizeUp;
            /// <summary>
            /// Provides access to the underlying input action "BrailleSettings/BrailleSizeDown".
            /// </summary>
            public InputAction @BrailleSizeDown => m_Wrapper.m_BrailleSettings_BrailleSizeDown;
            /// <summary>
            /// Provides access to the underlying input action "BrailleSettings/DotSizeUp".
            /// </summary>
            public InputAction @DotSizeUp => m_Wrapper.m_BrailleSettings_DotSizeUp;
            /// <summary>
            /// Provides access to the underlying input action "BrailleSettings/DotSizeDown".
            /// </summary>
            public InputAction @DotSizeDown => m_Wrapper.m_BrailleSettings_DotSizeDown;
            /// <summary>
            /// Provides access to the underlying input action "BrailleSettings/BrailleSpacingUp".
            /// </summary>
            public InputAction @BrailleSpacingUp => m_Wrapper.m_BrailleSettings_BrailleSpacingUp;
            /// <summary>
            /// Provides access to the underlying input action "BrailleSettings/BrailleSpacingDown".
            /// </summary>
            public InputAction @BrailleSpacingDown => m_Wrapper.m_BrailleSettings_BrailleSpacingDown;
            /// <summary>
            /// Provides access to the underlying input action "BrailleSettings/LineSpacingUp".
            /// </summary>
            public InputAction @LineSpacingUp => m_Wrapper.m_BrailleSettings_LineSpacingUp;
            /// <summary>
            /// Provides access to the underlying input action "BrailleSettings/LineSpacingDown".
            /// </summary>
            public InputAction @LineSpacingDown => m_Wrapper.m_BrailleSettings_LineSpacingDown;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_BrailleSettings; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="BrailleSettingsActions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(BrailleSettingsActions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="BrailleSettingsActions" />
            public void AddCallbacks(IBrailleSettingsActions instance)
            {
                if (instance == null || m_Wrapper.m_BrailleSettingsActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_BrailleSettingsActionsCallbackInterfaces.Add(instance);
                @BrailleSizeUp.started += instance.OnBrailleSizeUp;
                @BrailleSizeUp.performed += instance.OnBrailleSizeUp;
                @BrailleSizeUp.canceled += instance.OnBrailleSizeUp;
                @BrailleSizeDown.started += instance.OnBrailleSizeDown;
                @BrailleSizeDown.performed += instance.OnBrailleSizeDown;
                @BrailleSizeDown.canceled += instance.OnBrailleSizeDown;
                @DotSizeUp.started += instance.OnDotSizeUp;
                @DotSizeUp.performed += instance.OnDotSizeUp;
                @DotSizeUp.canceled += instance.OnDotSizeUp;
                @DotSizeDown.started += instance.OnDotSizeDown;
                @DotSizeDown.performed += instance.OnDotSizeDown;
                @DotSizeDown.canceled += instance.OnDotSizeDown;
                @BrailleSpacingUp.started += instance.OnBrailleSpacingUp;
                @BrailleSpacingUp.performed += instance.OnBrailleSpacingUp;
                @BrailleSpacingUp.canceled += instance.OnBrailleSpacingUp;
                @BrailleSpacingDown.started += instance.OnBrailleSpacingDown;
                @BrailleSpacingDown.performed += instance.OnBrailleSpacingDown;
                @BrailleSpacingDown.canceled += instance.OnBrailleSpacingDown;
                @LineSpacingUp.started += instance.OnLineSpacingUp;
                @LineSpacingUp.performed += instance.OnLineSpacingUp;
                @LineSpacingUp.canceled += instance.OnLineSpacingUp;
                @LineSpacingDown.started += instance.OnLineSpacingDown;
                @LineSpacingDown.performed += instance.OnLineSpacingDown;
                @LineSpacingDown.canceled += instance.OnLineSpacingDown;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="BrailleSettingsActions" />
            private void UnregisterCallbacks(IBrailleSettingsActions instance)
            {
                @BrailleSizeUp.started -= instance.OnBrailleSizeUp;
                @BrailleSizeUp.performed -= instance.OnBrailleSizeUp;
                @BrailleSizeUp.canceled -= instance.OnBrailleSizeUp;
                @BrailleSizeDown.started -= instance.OnBrailleSizeDown;
                @BrailleSizeDown.performed -= instance.OnBrailleSizeDown;
                @BrailleSizeDown.canceled -= instance.OnBrailleSizeDown;
                @DotSizeUp.started -= instance.OnDotSizeUp;
                @DotSizeUp.performed -= instance.OnDotSizeUp;
                @DotSizeUp.canceled -= instance.OnDotSizeUp;
                @DotSizeDown.started -= instance.OnDotSizeDown;
                @DotSizeDown.performed -= instance.OnDotSizeDown;
                @DotSizeDown.canceled -= instance.OnDotSizeDown;
                @BrailleSpacingUp.started -= instance.OnBrailleSpacingUp;
                @BrailleSpacingUp.performed -= instance.OnBrailleSpacingUp;
                @BrailleSpacingUp.canceled -= instance.OnBrailleSpacingUp;
                @BrailleSpacingDown.started -= instance.OnBrailleSpacingDown;
                @BrailleSpacingDown.performed -= instance.OnBrailleSpacingDown;
                @BrailleSpacingDown.canceled -= instance.OnBrailleSpacingDown;
                @LineSpacingUp.started -= instance.OnLineSpacingUp;
                @LineSpacingUp.performed -= instance.OnLineSpacingUp;
                @LineSpacingUp.canceled -= instance.OnLineSpacingUp;
                @LineSpacingDown.started -= instance.OnLineSpacingDown;
                @LineSpacingDown.performed -= instance.OnLineSpacingDown;
                @LineSpacingDown.canceled -= instance.OnLineSpacingDown;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="BrailleSettingsActions.UnregisterCallbacks(IBrailleSettingsActions)" />.
            /// </summary>
            /// <seealso cref="BrailleSettingsActions.UnregisterCallbacks(IBrailleSettingsActions)" />
            public void RemoveCallbacks(IBrailleSettingsActions instance)
            {
                if (m_Wrapper.m_BrailleSettingsActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="BrailleSettingsActions.AddCallbacks(IBrailleSettingsActions)" />
            /// <seealso cref="BrailleSettingsActions.RemoveCallbacks(IBrailleSettingsActions)" />
            /// <seealso cref="BrailleSettingsActions.UnregisterCallbacks(IBrailleSettingsActions)" />
            public void SetCallbacks(IBrailleSettingsActions instance)
            {
                foreach (var item in m_Wrapper.m_BrailleSettingsActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_BrailleSettingsActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="BrailleSettingsActions" /> instance referencing this action map.
        /// </summary>
        public BrailleSettingsActions @BrailleSettings => new BrailleSettingsActions(this);

        // Navigation
        private readonly InputActionMap m_Navigation;
        private List<INavigationActions> m_NavigationActionsCallbackInterfaces = new List<INavigationActions>();
        private readonly InputAction m_Navigation_next;
        private readonly InputAction m_Navigation_prev;
        private readonly InputAction m_Navigation_answer0;
        private readonly InputAction m_Navigation_answer1;
        private readonly InputAction m_Navigation_answer2;
        private readonly InputAction m_Navigation_answer3;
        private readonly InputAction m_Navigation_answer4;
        private readonly InputAction m_Navigation_answer5;
        private readonly InputAction m_Navigation_confirm;
        /// <summary>
        /// Provides access to input actions defined in input action map "Navigation".
        /// </summary>
        public struct NavigationActions
        {
            private @GameActions m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public NavigationActions(@GameActions wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "Navigation/next".
            /// </summary>
            public InputAction @next => m_Wrapper.m_Navigation_next;
            /// <summary>
            /// Provides access to the underlying input action "Navigation/prev".
            /// </summary>
            public InputAction @prev => m_Wrapper.m_Navigation_prev;
            /// <summary>
            /// Provides access to the underlying input action "Navigation/answer0".
            /// </summary>
            public InputAction @answer0 => m_Wrapper.m_Navigation_answer0;
            /// <summary>
            /// Provides access to the underlying input action "Navigation/answer1".
            /// </summary>
            public InputAction @answer1 => m_Wrapper.m_Navigation_answer1;
            /// <summary>
            /// Provides access to the underlying input action "Navigation/answer2".
            /// </summary>
            public InputAction @answer2 => m_Wrapper.m_Navigation_answer2;
            /// <summary>
            /// Provides access to the underlying input action "Navigation/answer3".
            /// </summary>
            public InputAction @answer3 => m_Wrapper.m_Navigation_answer3;
            /// <summary>
            /// Provides access to the underlying input action "Navigation/answer4".
            /// </summary>
            public InputAction @answer4 => m_Wrapper.m_Navigation_answer4;
            /// <summary>
            /// Provides access to the underlying input action "Navigation/answer5".
            /// </summary>
            public InputAction @answer5 => m_Wrapper.m_Navigation_answer5;
            /// <summary>
            /// Provides access to the underlying input action "Navigation/confirm".
            /// </summary>
            public InputAction @confirm => m_Wrapper.m_Navigation_confirm;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_Navigation; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="NavigationActions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(NavigationActions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="NavigationActions" />
            public void AddCallbacks(INavigationActions instance)
            {
                if (instance == null || m_Wrapper.m_NavigationActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_NavigationActionsCallbackInterfaces.Add(instance);
                @next.started += instance.OnNext;
                @next.performed += instance.OnNext;
                @next.canceled += instance.OnNext;
                @prev.started += instance.OnPrev;
                @prev.performed += instance.OnPrev;
                @prev.canceled += instance.OnPrev;
                @answer0.started += instance.OnAnswer0;
                @answer0.performed += instance.OnAnswer0;
                @answer0.canceled += instance.OnAnswer0;
                @answer1.started += instance.OnAnswer1;
                @answer1.performed += instance.OnAnswer1;
                @answer1.canceled += instance.OnAnswer1;
                @answer2.started += instance.OnAnswer2;
                @answer2.performed += instance.OnAnswer2;
                @answer2.canceled += instance.OnAnswer2;
                @answer3.started += instance.OnAnswer3;
                @answer3.performed += instance.OnAnswer3;
                @answer3.canceled += instance.OnAnswer3;
                @answer4.started += instance.OnAnswer4;
                @answer4.performed += instance.OnAnswer4;
                @answer4.canceled += instance.OnAnswer4;
                @answer5.started += instance.OnAnswer5;
                @answer5.performed += instance.OnAnswer5;
                @answer5.canceled += instance.OnAnswer5;
                @confirm.started += instance.OnConfirm;
                @confirm.performed += instance.OnConfirm;
                @confirm.canceled += instance.OnConfirm;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="NavigationActions" />
            private void UnregisterCallbacks(INavigationActions instance)
            {
                @next.started -= instance.OnNext;
                @next.performed -= instance.OnNext;
                @next.canceled -= instance.OnNext;
                @prev.started -= instance.OnPrev;
                @prev.performed -= instance.OnPrev;
                @prev.canceled -= instance.OnPrev;
                @answer0.started -= instance.OnAnswer0;
                @answer0.performed -= instance.OnAnswer0;
                @answer0.canceled -= instance.OnAnswer0;
                @answer1.started -= instance.OnAnswer1;
                @answer1.performed -= instance.OnAnswer1;
                @answer1.canceled -= instance.OnAnswer1;
                @answer2.started -= instance.OnAnswer2;
                @answer2.performed -= instance.OnAnswer2;
                @answer2.canceled -= instance.OnAnswer2;
                @answer3.started -= instance.OnAnswer3;
                @answer3.performed -= instance.OnAnswer3;
                @answer3.canceled -= instance.OnAnswer3;
                @answer4.started -= instance.OnAnswer4;
                @answer4.performed -= instance.OnAnswer4;
                @answer4.canceled -= instance.OnAnswer4;
                @answer5.started -= instance.OnAnswer5;
                @answer5.performed -= instance.OnAnswer5;
                @answer5.canceled -= instance.OnAnswer5;
                @confirm.started -= instance.OnConfirm;
                @confirm.performed -= instance.OnConfirm;
                @confirm.canceled -= instance.OnConfirm;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="NavigationActions.UnregisterCallbacks(INavigationActions)" />.
            /// </summary>
            /// <seealso cref="NavigationActions.UnregisterCallbacks(INavigationActions)" />
            public void RemoveCallbacks(INavigationActions instance)
            {
                if (m_Wrapper.m_NavigationActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="NavigationActions.AddCallbacks(INavigationActions)" />
            /// <seealso cref="NavigationActions.RemoveCallbacks(INavigationActions)" />
            /// <seealso cref="NavigationActions.UnregisterCallbacks(INavigationActions)" />
            public void SetCallbacks(INavigationActions instance)
            {
                foreach (var item in m_Wrapper.m_NavigationActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_NavigationActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="NavigationActions" /> instance referencing this action map.
        /// </summary>
        public NavigationActions @Navigation => new NavigationActions(this);
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "PerkinsBrailer" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="PerkinsBrailerActions.AddCallbacks(IPerkinsBrailerActions)" />
        /// <seealso cref="PerkinsBrailerActions.RemoveCallbacks(IPerkinsBrailerActions)" />
        public interface IPerkinsBrailerActions
        {
            /// <summary>
            /// Method invoked when associated input action "Dot0" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnDot0(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Dot1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnDot1(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Dot2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnDot2(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Dot3" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnDot3(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Dot4" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnDot4(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Dot5" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnDot5(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Space" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnSpace(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Delete" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnDelete(InputAction.CallbackContext context);
        }
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "BrailleSettings" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="BrailleSettingsActions.AddCallbacks(IBrailleSettingsActions)" />
        /// <seealso cref="BrailleSettingsActions.RemoveCallbacks(IBrailleSettingsActions)" />
        public interface IBrailleSettingsActions
        {
            /// <summary>
            /// Method invoked when associated input action "BrailleSizeUp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnBrailleSizeUp(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "BrailleSizeDown" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnBrailleSizeDown(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "DotSizeUp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnDotSizeUp(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "DotSizeDown" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnDotSizeDown(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "BrailleSpacingUp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnBrailleSpacingUp(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "BrailleSpacingDown" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnBrailleSpacingDown(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "LineSpacingUp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnLineSpacingUp(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "LineSpacingDown" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnLineSpacingDown(InputAction.CallbackContext context);
        }
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Navigation" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="NavigationActions.AddCallbacks(INavigationActions)" />
        /// <seealso cref="NavigationActions.RemoveCallbacks(INavigationActions)" />
        public interface INavigationActions
        {
            /// <summary>
            /// Method invoked when associated input action "next" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnNext(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "prev" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnPrev(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "answer0" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnAnswer0(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "answer1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnAnswer1(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "answer2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnAnswer2(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "answer3" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnAnswer3(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "answer4" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnAnswer4(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "answer5" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnAnswer5(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "confirm" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnConfirm(InputAction.CallbackContext context);
        }
    }
}
